# Generated by Django 2.2 on 2021-02-08 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_favoritesuperherolist_superhero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
