# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-09 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_delete_greeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superhero',
            old_name='descricao',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='superhero',
            name='photo',
            field=models.ImageField(upload_to='superheros'),
        ),
    ]
