# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-09 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20210208_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
