# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-09 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20210208_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritesuperherolist',
            name='superHero',
        ),
        migrations.RemoveField(
            model_name='favoritesuperherolist',
            name='user',
        ),
        migrations.AddField(
            model_name='superhero',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FavoriteSuperHeroList',
        ),
    ]
