# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-09 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20210208_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='photo',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
